version: '2'
services:
    jhipster_test-app:
        image: jhipster_test
        external_links:
            - jhipster_test-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster_test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_test-mysql:
        extends:
            file: mysql.yml
            service: jhipster_test-mysql
