version: '2'
services:
    jhipster_test-mysql:
        container_name: jhipster_test-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/jhipster_test/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipster_test
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
